Create image board
qpfmtlcp/django-board-practice pull request #27
Opened 2020-10-06 07:07 UTC by siransfe

Error occured
Board() got an unexpected keyword argument 'tagname'

2020-10-06 11:46 UTC, qpfmtlcp requested changes
현재 마스터랑 컨플릭트 해결 필요

2020-10-06 14:54 UTC, siransfe commented
## 문제 파악 완료/ 정리
model에 정의되지 않은 필드를 사용했으면
반드시 validated_data에서 pop을 해줘야 합니다! 
왜냐면 pop을 하지 않는다면 create를 할때 (database에 저장할때 없는 공간을 찾기 때문임)

2020-10-06 15:48 UTC, siransfe commented
## Remained issue

특정 tag 검색 시 해당 태그가 달린 board 전체 호출

2020-10-07 06:34 UTC, siransfe commented
이미지게시판 master와 병합 부탁드립니다.

2020-10-07 09:42 UTC, qpfmtlcp commented
@siransfe 
리뷰할 내용이 많아 qna 먼저 병합하고 진행할게요
#28 문제 먼저 해결해주세요

2020-10-07 12:20 UTC, qpfmtlcp reviewed
이 [commit](https://github.com/qpfmtlcp/django-board-practice/commit/61cd3b6390fd11f5c3bf531834c50031e7cd47b6) 참고하면
serializer에서 다른 방식으로 구현 가능

2020-10-11 02:47 UTC, merged